lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.AddUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug EventsWeb.Plugs.RequireAuth
  end

  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/login", PageController, :login
    resources "/users", UserController
    get "/users/:id/photo", UserController, :photo
    resources "/events", EventController
    resources "/comments", CommentController

    # Bellow session routing taken from Tuck notes 0302
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true

  end

  # Other scopes may use custom stacks.
  scope "/api", EventsWeb do
    pipe_through :api
    
    resources "/invites", InviteController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

lib/events/comments.ex
defmodule Events.Comments do
  @moduledoc """
  The Comments context.
  """

  import Ecto.Query, warn: false
  alias Events.Repo

  alias Events.Comments.Comment

  @doc """
  Returns the list of comments.

  ## Examples

      iex> list_comments()
      [%Comment{}, ...]

  """
  def list_comments do
    Repo.all(Comment)
  end

  @doc """
  Gets a single comment.

  Raises `Ecto.NoResultsError` if the Comment does not exist.

  ## Examples

      iex> get_comment!(123)
      %Comment{}

      iex> get_comment!(456)
      ** (Ecto.NoResultsError)

  """
  def get_comment!(id) do
    comment = Repo.get!(Comment, id)
    |> Repo.preload(:user)
    |> Repo.preload(:event)
    
    comment
  end

  @doc """
  Creates a comment.

  ## Examples

      iex> create_comment(%{field: value})
      {:ok, %Comment{}}

      iex> create_comment(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_comment(attrs \\ %{}) do
    %Comment{}
    |> Comment.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a comment.

  ## Examples

      iex> update_comment(comment, %{field: new_value})
      {:ok, %Comment{}}

      iex> update_comment(comment, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_comment(%Comment{} = comment, attrs) do
    comment
    |> Comment.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a comment.

  ## Examples

      iex> delete_comment(comment)
      {:ok, %Comment{}}

      iex> delete_comment(comment)
      {:error, %Ecto.Changeset{}}

  """
  def delete_comment(%Comment{} = comment) do
    Repo.delete(comment)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking comment changes.

  ## Examples

      iex> change_comment(comment)
      %Ecto.Changeset{data: %Comment{}}

  """
  def change_comment(%Comment{} = comment, attrs \\ %{}) do
    Comment.changeset(comment, attrs)
  end
end

lib/events/comments/comment.ex
defmodule Events.Comments.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :content, :string
    belongs_to :user, Events.Users.User
    belongs_to :event, Events.UserEvents.Event

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:content, :user_id, :event_id])
    |> validate_required([:content, :user_id, :event_id])
  end
end

lib/events_web/controllers/comment_controller.ex
defmodule EventsWeb.CommentController do
  use EventsWeb, :controller

  alias Events.Comments
  alias Events.Comments.Comment
  alias EventsWeb.Plugs

  # Comments can be created, edited, shown, and deleted only by logged in users
  plug Plugs.RequireLoggedIn, "en" when action in [:new, :create, :show, :edit, :update, :delete]

  # Add the comment onto the connection so that the next few plugs have access to the event
  plug Plugs.AddComment, "en" when action in [:edit, :update, :delete, :show]

  # Add the event onto the connection so that the next few plugs have access to the event
  plug Plugs.AddEvent, "en" when action in [:edit, :update, :delete, :show]

  # Comments can be deleted by the owner of the event and the owner of the comment
  plug Plugs.RequireSomeOwner, "en" when action in [:delete]

  # Comments can be editing by the owner of the comment only
  plug Plugs.RequireCommentOwner, "en" when action in [:edit, :update]

  def index(conn, _params) do
    comments = Comments.list_comments()
    render(conn, "index.html", comments: comments)
  end

  def new(conn, _params) do
    changeset = Comments.change_comment(%Comment{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"comment" => comment_params}) do
    # Add the user_id and event_id into the comment
    updated_params = comment_params
    |> Map.put("user_id", conn.assigns[:user].id)

    event_id = comment_params["event_id"]
    event = Events.UserEvents.get_event(event_id)

    case Comments.create_comment(updated_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    render(conn, "show.html", comment: comment)
  end

  def edit(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    changeset = Comments.change_comment(comment)
    render(conn, "edit.html", comment: comment, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}) do
    comment = Comments.get_comment!(id)
    event = comment.event

    case Comments.update_comment(comment, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = Comments.get_comment!(id)
    event = comment.event
    {:ok, _comment} = Comments.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :show, event))
  end
end

lib/events_web/views/comment_view.ex
defmodule EventsWeb.CommentView do
  use EventsWeb, :view
end

lib/events_web/templates/comment/edit.html.eex
<h1>Edit Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :update, @comment)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

lib/events_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <% IO.inspect @changeset %>
  <%= hidden_input f, :event_id %>
  <%= error_tag f, :event_id %>

  <div class="w-50">
    <div class="mb-3">
      <%= text_input f, :content, class: "form-control" %>
    </div>
    <%= error_tag f, :content %>

    <div>
        <%= submit "Post", type: "submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

lib/events_web/templates/comment/index.html.eex
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.content %></td>

      <td>
        <span><%= link "Show", to: Routes.comment_path(@conn, :show, comment) %></span>
        <span><%= link "Edit", to: Routes.comment_path(@conn, :edit, comment) %></span>
        <span><%= link "Delete", to: Routes.comment_path(@conn, :delete, comment), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Comment", to: Routes.comment_path(@conn, :new) %></span>

lib/events_web/templates/comment/new.html.eex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

lib/events_web/templates/comment/show.html.eex
<h1>Show Comment</h1>

<ul>

  <li>
    <strong>Content:</strong>
    <%= @comment.content %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.comment_path(@conn, :edit, @comment) %></span>
<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>