lib/events_web/router.ex
defmodule EventsWeb.Router do
  use EventsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug EventsWeb.Plugs.AddUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug EventsWeb.Plugs.RequireAuth
  end

  scope "/", EventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/login", PageController, :login
    resources "/users", UserController
    get "/users/:id/photo", UserController, :photo
    resources "/events", EventController
    resources "/comments", CommentController

    # Bellow session routing taken from Tuck notes 0302
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true

  end

  # Other scopes may use custom stacks.
  scope "/api", EventsWeb do
    pipe_through :api
    
    resources "/invites", InviteController, except: [:new, :edit]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: EventsWeb.Telemetry
    end
  end
end

lib/events_web/templates/page/index.html.eex
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Events</h1>
    </div>
  </div>
  <div class="row">
    <%= for event <- @events do %>
      <div class="card m-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title text-capitalize"><%= event.name %></h5>
          <p class="mb-2 fs-6 text-muted"><%= event.date %></p>
          <p class="card-text"><%= event.description %></p>
          <span class="mx-1"><%= link "Show", to: Routes.event_path(@conn, :show, event) %></span>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col m-4">
      <%= link "New Event", to: Routes.event_path(@conn, :new) %>
    </div>
  </div>
</div>

lib/events_web/templates/page/login.html.eex
<div class="container w-50">
  <div class="row mb-1">
    <div class="col">
      <% redirect_uri = get_redirect_uri(@conn) %>
      <%= if redirect_uri do %>
        <%= form_for @conn, Routes.session_path(@conn, :create, redirect: redirect_uri), fn f -> %>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <%= text_input f, :email, placeholder: "email", class: "form-control", id: "exampleInputEmail1" %>
          </div>
          <div class="mb-3">
            <%= submit "Log In" , type: "submit", class: "btn btn-primary" %>
          </div>
        <% end %>
          
      <% else %>
        <%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <%= text_input f, :email, placeholder: "email", class: "form-control", id: "exampleInputEmail1" %>
          </div>
          <div class="mb-3">
            <%= submit "Log In" , type: "submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= if redirect_uri do %>
        <%= link("Register", class: "btn btn-primary", to: Routes.user_path(@conn, :new, redirect: redirect_uri)) %>
      <% else %>
        <%= link("Register", class: "btn btn-primary", to: Routes.user_path(@conn, :new, redirect: redirect_uri), method: "get") %>
      <% end %>

    </div>
  </div>
</div>